[package]
name = "lumen-app"
version.workspace = true
edition.workspace = true

[dependencies]
lumen-core = { workspace = true }
lumen-render = { workspace = true }
eframe = { workspace = true }
egui = { workspace = true }
anyhow = { workspace = true }
# 钉住传递依赖，阻止 Cargo 拉 edition2024 包
url = { workspace = true }
idna = { workspace = true }
webbrowser = { workspace = true }
getrandom = { workspace = true }
unicode-segmentation = { workspace = true }

